---
name: "✅ Project Submission"
about: Use this template to submit your project
title: TEAM NAME - PROJECT NAME
labels: submission
# assignees:

---

**Before you start, please follow this format for your issue title**:
TEAM NAME - PROJECT NAME

## ℹ️ Project information
_Please complete all applicable._

- **Project Name**:
- **Short Project Description**: _One line crisp description of your project_
- **Team Name**:
- **Team Members**: _Mention their Names & tag their GitHub handles_
- **Where to find you?**: _Mention the room you're sitting in so we can find you_
- **Demo Link**: _(if any, this might contain a website/ mobile application link/ short video, etc.)_
- **Repository Link(s)**: _Provide us the link to your code. All judges must be able to access it._
- **Prize Categories Enrolled for**:
   (Please tick any specific Category that applies)
  - [ ] Best use of Microsoft Azure
  - [ ] Best Beginner (Your team should be atleast 50% Beginners)
  - [ ] Best "Jugaad" - Best Fun/ Silly/ Innovative Hack
  - [ ] Best UIPath Hack

## 🔥 Your Pitch
_Kindly write a pitch for your project. Please do not use more than 500 words_


## 🔦 Any other specific thing you want to highlight?
_(Optional)_

## ✅ Checklist

**Before you post the issue**:
- [ ] You have followed the issue title format.
- [ ] You have mentioned the correct labels.
- [ ] You have provided all the information correctly.
